### ISSUE TITLE
pycbc_generate_hwinj specification of long_asc_nodes

### ISSUE THREAD

**Issue by SergeiOssokine** [gwastro/pycbc#1736]
One of the options that can be passed to get_td_waveform is long_asc_nodes which is useful in some circumstances. Currently, it seems this option is not propagated to  pycbc_generate_hwinj . It would be great if this option can be added so that there is more freedom when generating frames.

**Comment by spxiwh** [comment]
There's no way of storing this in the produced XML file. So I'l prefer to put this on hold until we have a better replacement for XML files.

**Comment by SergeiOssokine** [comment]
Sorry, I am a bit confused Ian. Do you mean that the generated .xml injection file can't have arbitrary new columns?

**Comment by spxiwh** [comment]
Yes ... It's easy to add columns to python, but the C-code is horrendous (although really fast). Also it makes things backwards incompatible in weird ways, and therefore requires a large LIGO agreement.

.... Which is why we plan to retire XML in PyCBC in favour of HDF injection files. No-one's found the time to do that yet though.

**Comment by SergeiOssokine** [comment]
Ah I see. For the things that I am doing, I really do need to do this, so I think I will just work on a fork for now. Thanks for the explanation. Funnily I don't actually care if the value is added to the xml file, I just need the freedom in the call to get_td_waveform (for this project, the waveform is stored elsewhere if we ever need it).

**Comment by ahnitz** [comment]
I think this has likely been superseded by hdf injection support. If in error, please re-open.
