### ISSUE TITLE
lalsuite installation for pycbc fails at "make"

### ISSUE THREAD

**Issue by santanu-tripathy** [gwastro/pycbc#2231]
After configuring lalsuite in virtualenv, the make fails with the following error..

make[6]: Entering directory `/home/ldap_users/st12rs048/cluster-pycbc/src/lalsuite/lalsimulation/src'
  CC       LALSimIMRNRWaveforms.lo
LALSimIMRNRWaveforms.c: In function ‘XLALSimInspiralNRWaveformCheckFRef’:
LALSimIMRNRWaveforms.c:74:5: error: implicit declaration of function ‘ReadHDF5RealVectorDataset’ [-Werror=implicit-function-declaration]
     ReadHDF5RealVectorDataset(omega_group, "Y", &omega_w_vec);
     ^
LALSimIMRNRWaveforms.c:74:5: error: nested extern declaration of ‘ReadHDF5RealVectorDataset’ [-Werror=nested-externs]
LALSimIMRNRWaveforms.c: At top level:
cc1: error: unrecognized command line option "-Wno-misleading-indentation" [-Werror]
cc1: all warnings being treated as errors
make[6]: *** [LALSimIMRNRWaveforms.lo] Error 1
make[6]: Leaving directory `/home/ldap_users/st12rs048/cluster-pycbc/src/lalsuite/lalsimulation/src'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/home/ldap_users/st12rs048/cluster-pycbc/src/lalsuite/lalsimulation/src'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/home/ldap_users/st12rs048/cluster-pycbc/src/lalsuite/lalsimulation/src'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/ldap_users/st12rs048/cluster-pycbc/src/lalsuite/lalsimulation'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/ldap_users/st12rs048/cluster-pycbc/src/lalsuite/lalsimulation'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ldap_users/st12rs048/cluster-pycbc/src/lalsuite'
make: *** [all] Error 2

I am using CentOS 7 64 bit machine

**Comment by ahnitz** [comment]
Hi @santanu-tripathy. This looks like an issue with building lalsuite. Do you need to build from source, or are any of the prebuilt options sufficient? (i.e. the version distributed through pypi). There are also rpms / deb images built for RHEL7 / Debian 9 which you may find. 
```
pip install lalsuite
```
The error itself seems to be related to the gcc version you are using. Is this gcc 6? Also, this isn't really the support forum for lalsuite, you may want to try contacting them directly.

https://wiki.ligo.org/DASWG/LALSuite

**Comment by spxiwh** [comment]
As Alex said, this probably isn't the right forum for this discussion ... But as I wrote the `LALSimIMRNRWaveforms.c` code that seems to be failing let me chime in.

I disagree with Alex's hypothesis that this is related to the GCC version (the `-Wno-misleading-indentation` stuff is *not* causing the failure, the failure is `error: implicit declaration of function ‘ReadHDF5RealVectorDataset’`). I think that you are trying to build lalsuite without HDF support (either because you disabled it, or because lalsuite couldn't find HDF .... If the latter check the config.log file). This should still allow the build to succeed, but I guess I have to fix something in this code ... I'll look into that. Nevertheless, PyCBC does require a HDF-enabled build of lalsuite for a couple of the waveform models, so it is not recommended to build lalsuite in this way.
