### ISSUE TITLE
Weave broken with current numpy

### ISSUE THREAD

**Issue by ahnitz** [gwastro/pycbc#2470]
This requires a new release of weave
See https://github.com/scipy/weave/issues/11

However, I think we should drop weave support before this probably happens. I could use some help. Can someone handle the decompress function and threshold functions? I can handle the chisq one.

**Comment by dbkeitel** [comment]
@ahnitz : I'm running into the `cannot import name _get_ndarray_c_version` with a fresh venv, 
```
virtualenv --no-site-packages pycbc-venv
source pycbc-venv/bin/activate
pip install pycbc
```
since it seems the `numpy>=1.13.0,<1.15.3` in the current requirements.txt is not yet enforced in the latest 1.13.2 release and the problematic 1.16.0 is pulled in instead:
```
pip list
[...]
numpy                         1.16.0    
[...]
PyCBC                         1.13.2
```

Is a proper fix imminent, or could just fixing the version requirement be considered sufficient reason for a new point release?

In the meantime, manually downgrading
```
pip install --upgrade numpy==1.15.3
```
seems to work for me.

**Comment by ahnitz** [comment]
@dbkeitel Indeed, 1.16.0 is a recent release, and we've updated requirements.txt to handle this.

**Comment by dbkeitel** [comment]
@ahnitz Thanks for the quick reply. What I'm asking is whether you're planning a pycbc-1.13.3 (or 1.13.2.1 or whatever) minor release to pick up that requirements change, or whether "manually downgrade numpy" is the recommended short-term solution?

**Comment by ahnitz** [comment]
@dbkeitel I'm hoping to get rid of weave shortly, and we'll have a release after that which should resolve this issue. If that looks like it will be significantly delayed we can consider putting out a point release to work around the change in the numpy API.

**Comment by dbkeitel** [comment]
Ok thanks, good enough for me.

**Comment by spxiwh** [comment]
Alex, can we cut a release now before looking to remove weave (which would be 1.14 anyway). Would also be good to get the astropy-being-way-too-slow fixes in the latest release as well.

.... Still swamped for at least another week on my end.

**Comment by josh-willis** [comment]
@ahnitz @cdcapano As I mentioned in #2453, I don't want the waveform compression stuff changed until that merge request is completed, and things are rebased off of it.  I already spent quite a lot of time this fall fixing the merge conflicts that result when that change is compared against something that touches those files, since the file layout necessarily changes as part of adding in the CUDA support.  It will be much easier to do in that order.

**Comment by ahnitz** [comment]
This is now fixed by requiring specific numpy versions.
