### ISSUE TITLE
multi ifo code should track foreground exclusive livetime

### ISSUE THREAD

**Issue by ahnitz** [gwastro/pycbc#2727]
The foreground livetime is calculated here 

https://github.com/gwastro/pycbc/blob/master/bin/hdfcoinc/pycbc_multiifo_coinc_statmap#L236

However, this does not get recalculating in combine statmap here. 

https://github.com/gwastro/pycbc/blob/master/bin/hdfcoinc/pycbc_multiifo_combine_statmap

It should be done so that downstream codes (such as VT plots) can be made.

**Comment by tdent** [comment]
Partly fixed by #2773 however we ideally we will want to restrict the 'censored' times to only significant fg triggers (say, FAR<1/week).  To be addressed in the combine_statmap code.

**Comment by tdent** [comment]
I think after https://github.com/gwastro/pycbc/pull/2784/files we're passing this over to you (@ahnitz ). 

One other aspect, we're wondering if the foreground censor should be defined before or after clustering over coinc types.  Since the post-clustering coinc list is the one shown on the loudest event page it may be preferable to use that one.  In that case the exc foreground segments & time should be (re)calculated after clustering.

**Comment by tdent** [comment]
Fixed by #2815 and #2817.
