### ISSUE TITLE
qtransform of 50Hz signal

### ISSUE THREAD

**Issue by matxil** [gwastro/pycbc#2789]
Hi, 

I have a very simple code in which I generate a simple 50 Hz signal, which I use to check basic operations in pycbc and GWpy. When I send this to qtransform, I naively would expect a horizontal line at f = 50Hz. Instead, qtransform gets blocked completely so in the end I have to kill the entire process.
Is this because the signal is too simple? In general, I often have this problem with qtransform blocking, which is why I use this test signal in the first place to get a feeling for what's going on.  

```
import numpy as np
import matplotlib.pyplot as plot
import pylab
from gwpy.timeseries import TimeSeries

twopi = 2*np.pi     # 6.2 seconds
delta_t = 0.00001
sample_rate = 1.0/delta_t
duration = 100.0
nice_time = 6.28320     # so number of bins can be divided by 4 or 5
signal = np.arange(0, nice_time, delta_t);
sine_50Hz = 50.0 * np.sin(50.0*twopi*signal)       # 50Hz

ts_50Hz_GWpy = TimeSeries( sine_50Hz, sample_rate=sample_rate, unit='s')
ts_50Hz_pycbc = TimeSeries.to_pycbc(ts_50Hz_GWpy)
whitePyCbc = ts_50Hz_pycbc.whiten(4, 2)

times, freqs, power = whitePyCbc.qtransform( logfsteps=10, qrange=(8, 8), frange=(20, 512) )
pylab.figure(figsize=[7, 5])
pylab.pcolormesh(times, freqs, power**0.5)
pylab.yscale('log')
pylab.ylabel("Wh Frequency (Hz)")
pylab.show(False)
```

**Comment by ahnitz** [comment]
@matxil Here's a mildly modified version of your script. 

I'm not sure I can reproduce the blocking, but the image I got by running your code, I think not
behave as you expect i.e. you would not see a line at 50 Hz. This occurs because the
qtransform normalizes by the energy in a frequency bin normally, and you are also applying
whitening to the data. This will suppress the line itself. You can get the line to show up as you
expect as follows by taking out the whitening stage (which *is* something useful for analyzing real
data to flatten out the noise spectrum), and by using a keyword argument to get the raw
complex values back. These aren't prenormalized, so we can just skip the frequency normalization and plot the amplitude directly. 

```
import numpy as np
import pylab
from pycbc.types import TimeSeries

twopi = 2*np.pi     # 6.2 seconds
delta_t = 0.00001
nice_time = 6.28320     # so number of bins can be divided by 4 or 5
signal = np.arange(0, nice_time, delta_t);
sine_50Hz = 50.0 * np.sin(50.0*twopi*signal)       # 50Hz

ts = TimeSeries(sine_50Hz, delta_t=delta_t)

times, freqs, power = ts.qtransform(delta_t=.01,
                                           logfsteps=100,
                                           qrange=(8, 8), 
                                           frange=(20, 100),
                                           return_complex=True)
pylab.figure(2, figsize=[7, 5])
pylab.pcolormesh(times, freqs, abs(power)**0.5)
pylab.colorbar()
pylab.yscale('log')
pylab.ylabel("Wh Frequency (Hz)")
```
It produces this image. 
![download (2)](https://user-images.githubusercontent.com/2206534/59786999-c9e73c80-92c8-11e9-8847-e4d96849bd5f.png)

Now you can see the 50 Hz line, although it is very broad. Keep in mind this is using q-tiles which cover some range of frequency and time bandwidth. You can narrow the frequency resolution by raising the
q-value as below. 

```
times, freqs, power = ts.qtransform(delta_t=.01,
                                           logfsteps=100,
                                           qrange=(20, 20), 
                                           frange=(20, 100),
                                           return_complex=True)
pylab.figure(2, figsize=[7, 5])
pylab.pcolormesh(times, freqs, abs(power)**0.5)
pylab.colorbar()
pylab.yscale('log')
pylab.ylabel("Wh Frequency (Hz)")
```
![download (3)](https://user-images.githubusercontent.com/2206534/59787008-cc499680-92c8-11e9-8ed7-0121caa2ac84.png)

* Some other notes from your script. The 'logfsteps' option is basically a way to reduce the size of the return output. It's interpolated to a 2-d array, and this just ensures the freqeuncy spacing is logarithmic and that the frequency dimension is that long. There is a detla_t option that similarly choosing the time
resolution to interpolate the q-plane into an image.

**Comment by ahnitz** [comment]
@matxil I should add, in the common case, the auto normalization is desired since we are looking for time localized changes in the power at some frequency, not a constant sine wave.

**Comment by matxil** [comment]
Hi Alex, 

Thank you for your very complete answer. You're right that after whitening of course the signal should disappear. As a matter of fact, I tried the same code without whitening, and for signals with varying frequencies and even with a fake chirp signal but the problem in all these cases was that the qtransform "hangs" and then I would have to kill my process. That's why I wanted to go to the simplest possible signal. 
If you cannot reproduce the blocking, could you guess what might be the problem? In some cases it makes my computer hang and I even have to reboot. Could it be that with an almost empty signal, somehow the Fourier transform gets into an eternal loop or something? 
Anyway, thanks again for your comments because it made some aspects of what q-transform does clearer to me. 

Cheers, 

Machiel

**Comment by matxil** [comment]
I just made a few checks using your code to start with and Qtransform does not "hang" anymore, so I guess I must have done something wrong in my calls to Qtransform before which is cured by now. 
Thank you very much for your help.

**Comment by ahnitz** [comment]
@matxil One thing that comes to mind is that qtransform is somewhat of a memory hog. Is it possible that it was using up most of the available memory on your machine (maybe going into swap even)? That might drastically slow it down so it appears to hang.
