### ISSUE TITLE
Average time in multiifo statmap inj may not be correct

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#2824]
See https://github.com/gwastro/pycbc/blob/master/bin/hdfcoinc/pycbc_multiifo_coinc_statmap_inj#L98 
is this correct in cases where there may be ifo-time = -1 sentinel values?

**Comment by ahnitz** [comment]
@tdent I think you may be right. The effect this should have is that injections aren't really going to get their 'inclusive' background calculated correctly (i.e. not at all really). It may not be obvious in the current output results that anything is amiss, but my expectation is that some injections will have identical ifar and ifar_exc valuees.

**Comment by GarethDaviesGW** [comment]
Are we looking at the specific linked line `ifar_exc = background_time / (fnlouder_exc + 1)` here or at the mean calculation a few lines after

The mean calculation later should not have any of the -1 values as the statmap_inj is only acting on the specific IFO combination, or am I missing something?

Otherwise I don't see how the linked line will be affected by the -1 times

**Comment by tdent** [comment]
Gareth, the link was put there on Jul 3, for the version of the code at that point

**Comment by tdent** [comment]
anyway, yes, of course it was referring to a calculation of mean times `ftimes = numpy.concatenate(ifotimes).mean(axis=0)`

**Comment by tdent** [comment]
if you don't think this is a problem (i.e. you *know* that there will be no -1 values at this point) then can close this issue

**Comment by GarethDaviesGW** [comment]
Okay, that's what I thought, but as I couldn't see any issue with the calculation (No -1s should be present at this point), I'd confused myself
