### ISSUE TITLE
LIGO sample rate is hardcoded in simulated noise

### ISSUE THREAD

**Issue by spxiwh** [gwastro/pycbc#3250]
If using simulated noise, the sample_rate is hardcoded to 16384:

https://github.com/gwastro/pycbc/compare/master...spxiwh:basic_lisa_detector_hack?expand=1#diff-f7c48693e4cf0e4ed81e7c5663732255L31

This will cause memory allocation errors if trying to generate LISA simulated noise with a very small delta-f.

**Comment by spxiwh** [comment]
It's also harcoded here too:
https://github.com/gwastro/pycbc/compare/master...spxiwh:basic_lisa_detector_hack?expand=1#diff-e5671d49054b6ec5839900dbf9229c20L369

**Comment by spxiwh** [comment]
And perhaps here, though I can't remember why I needed to change this:
https://github.com/gwastro/pycbc/compare/master...spxiwh:basic_lisa_detector_hack?expand=1#diff-e5671d49054b6ec5839900dbf9229c20L355

**Comment by ahnitz** [comment]
This requires a bit of thought as to how to present this to the user. The reason it is hardcoded is there needs to be a deterministic set of random numbers. Otherwise, the data is not reproduceable for different time stretches. An obvious solution would be to make it clear that you only get reproduceable data sets if both the seed *and* the sample rate are the same. 

So

1) Add argument to choose sample rate
2) check in upstream executables / higher level code make sure this can be set independently from the returned data sample rate (for example,  when using the strain.from_cli function)

**Comment by spxiwh** [comment]
Could add an additional optional argument to specify the sample rate to use for generating the simulated data, to ensure reproduceable output. .... And raise a nice big warning if not giving that option and then using LISA-like delta_f s!

**Comment by ahnitz** [comment]
This has been addressed.
