### ISSUE TITLE
Lots of zeros in SNR when use dynesty as the sampler.

### ISSUE THREAD

**Issue by yanyuechuixue** [gwastro/pycbc#3268]
When one  runs pycbc_inference with Dynesty as the sampler, he will get the posteriors of "loglikelihood". It has a lot of '-1E300' values:

![image.png](https://i.loli.net/2020/05/12/ujpnli2JacSb53X.png)

When I try to use the function "snr_from_loglr(loglikelihood-lognl)" to get the posterior of SNR, those '-1E300' results in a lot of zeros in SNR. It seems like:

![image.png](https://i.loli.net/2020/05/12/hquAK9wtRdTPibQ.png)

In my opinion, this is a kind of weird.
So I want to ask, if I want to calculate the errorbar of SNR, should I drop those zero values?

Thanks a lot!

**Comment by cdcapano** [comment]
Those points are places in parameter space where the likelihood is basically 0, giving log likelihood of -inf (I think hdf files store "inf" as the largest possible float it can store, which is why you're seeing -1e300 there). The SNR for these are reported as 0 because SNR is defined as `\sqrt(2*loglr)`, where loglr is the log likelihood ratio. As you can see,  SNR only has any meaning for positive values of the loglr. So as not to give imaginary values, the `snr_from_loglr` function just returns 0 for negative values of the loglr. I would just exclude those points.

That said, I'm not quite certain what you mean by "errorbar on the SNR". SNR arises from maximizing the log likelihood ratio; it really only has meaning for the maximum likelihood point.

**Comment by yanyuechuixue** [comment]
Thank you!
