### ISSUE TITLE
Illegal Instruction during import

### ISSUE THREAD

**Issue by niklasrb** [gwastro/pycbc#3875]
Hey everyone,
I've been trying to do some inference with pycbc and lalsuite on our university cluster, but unfortunately I get some errors that I couldn't explain yet. 
Whenever I run _import pycbc.events_ in python I get an "Illegal Instruction" and the python execution just stops. I've managed to track down the callstack to 
```
~/GWsoftware/inference$  python3 -m pdb test.py  # contains "import pycbc.events"
...
(Pdb) bt
  /home/nbecker/.miniconda3/envs/lalsuite-dev/lib/python3.9/bdb.py(580)run()
-> exec(cmd, globals, locals)
  <string>(1)<module>()
  /home/nbecker/GWsoftware/inference/test.py(2)<module>()
-> import pycbc.events
  <frozen importlib._bootstrap>(1007)_find_and_load()
  <frozen importlib._bootstrap>(986)_find_and_load_unlocked()
  <frozen importlib._bootstrap>(680)_load_unlocked()
  <frozen importlib._bootstrap_external>(850)exec_module()
  <frozen importlib._bootstrap>(228)_call_with_frames_removed()
  /home/nbecker/GWsoftware/pycbc/pycbc/events/__init__.py(5)<module>()
-> from .eventmgr import *
  <frozen importlib._bootstrap>(1007)_find_and_load()
  <frozen importlib._bootstrap>(986)_find_and_load_unlocked()
  <frozen importlib._bootstrap>(680)_load_unlocked()
  <frozen importlib._bootstrap_external>(850)exec_module()
  <frozen importlib._bootstrap>(228)_call_with_frames_removed()
  /home/nbecker/GWsoftware/pycbc/pycbc/events/eventmgr.py(39)<module>()
-> from .eventmgr_cython import findchirp_cluster_over_window_cython
  <frozen importlib._bootstrap>(1007)_find_and_load()
  <frozen importlib._bootstrap>(986)_find_and_load_unlocked()
  <frozen importlib._bootstrap>(680)_load_unlocked()
  <frozen importlib._bootstrap_external>(1181)exec_module()
> <frozen importlib._bootstrap>(220)_call_with_frames_removed()
(Pdb) s
> <frozen importlib._bootstrap>(228)_call_with_frames_removed()
(Pdb) s
Illegal instruction
~/GWsoftware/inference$ 
```

So I guess the error is somehow connected to cython, but I wasn't able to track it further. 
I installed the conda environment from [here](https://git.ligo.org/lscsoft/lalsuite/-/blob/master/conda/environment.yml) and installed pycbc with "pip install -e .". 
If anyone has any pointers, they would be much appreciated!
Thanks and best,
Niklas

**Comment by ahnitz** [comment]
@niklasrb Interesting, illegal instruction usually implies precompiled code used instructions that your CPU doesn't support. However, if you installed from source (which it looks like from your comment) then it shouldn't have been able to build on that machine to begin with,.

What is the CPU you are running on? That might give an idea.

**Comment by niklasrb** [comment]
> What is the CPU you are running on? That might give an idea.

It should be an AMD Opteron Processor 2427

**Comment by ahnitz** [comment]
Ok, I just checked. I think I have a guess here. That processor lacks SSE4.2 and AVX. I think our explicit AVX code should all have fallbacks that don't require AVX and should not be the issue here. I'm going to guess though that SSE4.2 is the problem. We compile our cython extensions with SSE4.2 support enabled explicitly, but don't use those instructions directly, so you should be able to disable this. See e.g. 

https://github.com/gwastro/pycbc/blob/master/setup.py#L215

@niklasrb Depending on your comfort level, you can verify if this is the issue by changing the line to sse4 or just commenting out the section in its entirety so no SSE is enabled. You'd have to then reinstall pycbc from source. I'm not sure the way python handles extensions would notice a change like this, so you may need to ensure you reinstall without using cached build products. (i.e. --no-cache-dir).

**Comment by ahnitz** [comment]
@niklasrb If this is the issue, we can probably patch this to detect the SSE level of the machine when doing a source install and have a fallback setting. Unfortunately, this means you'd always have to install PyCBC from source as the distributed packages currently have SSE4.2 as a minimum vector instruction requirement. 

@josh-willis Is there much difference between how well gcc optimizes between SSE4.2 or SSE4?

**Comment by niklasrb** [comment]
>  just commenting out the section in its entirety so no SSE is enabled.

This together with a fresh repo clone worked! Thank you very much!
