### ISSUE TITLE
Conflict with multiprocessing and the pycbc.detector.Detector class 

### ISSUE THREAD

**Issue by nmutto** [gwastro/pycbc#3920]
Hi. I am trying to parallelise my code using the `multiprocessing` library. For instance, one of the first operations that I want to perform in parallel is the creation of objects whose class makes use of some `pycbc` modules. When I set up the code to use `multiprocessing` for this task, e.g.

    import multiprocessing as mp
    with mp.Pool(2) as pool:
        list_of_objects = pool.map(function_that_creates_objects, list_of_inputs_for_my_class)

I get the following error:

`TypeError :  cannot pickle 'lal.Detector' object`

So I thought that maybe it is related to the `detector.py` module of the `pycbc` library. After some research on the web about this kind of error, I ended up in using `dill` as a "debugger" (as shown [here](https://stackoverflow.com/questions/17872056/how-to-check-if-an-object-is-pickleable)) to see where the problem was. `dill` pointed to the `pycbc.detector.Detector` class. In fact, one can quickly check it by making a short script like the following:

    from pycbc.detector import Detector
    import dill
    dill.pickles(Detector("L1"))

The `False` output means that it can not be pickled and should lead to the `TypeError` above when `multiprocessing` is involved. Eventually I found that the attribute

`self._lal = lalsim.DetectorPrefixToLALDetector(self.name)`

of the `Detector` class is responsible of all the troubles, and by editing the class in this way

    self._lal = lalsim.DetectorPrefixToLALDetector(self.name)
    self.response = self._lal.response
    self.location = self._lal.location
    # I added the following line of code
    del self._lal

I was able to bypass the problem and parallelise my code.  Since this is my first approach to parallel coding, maybe I am doing something in the wrong way, but I thought that it might be also interesting for you to know this issue. Do you think that it can be fixed in future updates? I hope that everything is clear, if not feel free to ask. Many thanks in advance.

I ran these tests on macOS Monterey 12.1, using `python 3.8.12` and `pycbc 1.18.3` (but the same problem occurs also with `pycbc 2.0.1`)

**Comment by spxiwh** [comment]
@nmutto Thanks for reporting this. This is a "known" issue, but you're into quite advanced use cases here, and it's not always easy to document strange cases like this one.

The basic issue here is that the lal Detector object cannot be pickled, which is required for multiprocessing. Your fix works for your use case by forcing the code to recompute this on every thread when multiprocessing, but it wouldn't work in all cases. (An example of something that would fail is if you try to use `Detector.project_wave` after doing this, and that method is quite important in many applications). This isn't trivial to fix because the underlying problem is not in PyCBC, but in lal. We use lal (the LIGO/Virgo software stack) to tell us the exact location and orientation of LIGO and Virgo and use some of its routines for projecting gravitational wave polarizations into a detector response. This requires using the Detector object. I think the only way we could avoid this happening generically is by not storing the lal object at all (which has a performance penalty), or by somehow deleting it when starting multiprocessing (which I don't know how to automate).

A workaround to this is to *not* create the pycbc Detector object *outside* of a multiprocessing loop. If you need to use a Detector object within multiprocessing create the Detector object within the loop. This causes it to be created on each thread in use, and avoids this problem. ... In your use case that would mean move the `H1 = detector.Detector('H1')` line to within the  `function_that_creates_objects`.

**Comment by nmutto** [comment]
@spxiwh Thank you for your answer and the suggestion. However, I am afraid that I can not apply it to my specific case, since I am not creating the Detector object by myself. In fact, one of the attributes of my class points to a `FDomainDetFrameGenerator` object to project GW signals in different detectors (in frequency domain), and as far as I understand it, the Detector object is created automatically by `pycbc` when I initialise the `FDomainDetFrameGenerator` object. Just to be clear, this is what I am doing:

        self.generator = FDomainDetFrameGenerator(rFrameGeneratorClass = FDomainCBCGenerator,
                                                  epoch = self.t_gps.value,
                                                  variable_args = ["mass1", "mass2", "spin1z", "spin2z", "distance", "inclination", "coa_phase","tc", "ra", "dec", "polarization"],
                                                  detectors = self.detectors,
                                                  delta_f = self.frequency_resolution.value,
                                                  f_lower = self.start_frequency.value,
                                                  approximant = self.approximant)
 
I am quite sure that The `Detector.project_wave` method that you mentioned is not involved here since, I think, it is only related to time-domain waveforms, which I do not require in my code. But since you told me that my workaround may lead to some unexpected fails, is it possible that by deleting the `self._lal` attribute I am somehow affecting also the GW projections in frequency domain? Also, is there a way to know which other methods besides `Detector.project_wave` are going to be affected by this workaround? Thank you.

**Comment by spxiwh** [comment]
@nmutto Thanks for the details here. We do have one use-case (pycbc_inference) where the `FDomainDetFrameGenerator` is used across multiple processes. In this case the generator, and indeed all of it's inputs, are created on *each* of the processes. I'm not sure if you could move the creation of the `FDomainDetFrameGenerator` inside the parallel loop?

The project_wave method is used to convert h_+ and h_x to h(t) in a detector. The most accurate way of doing this is to convert to the time domain and use lalsimulation, but for most use cases (e.g. a minute-long CBC waveform on the Earth) this is not needed, and often the detector would be assumed to be stationary and simpler computations (not needing the `_lal` object) can be done. Looking over the code, I think that only `project_wave` with `method=lal` would be affected by the workaround you propose. I am also pretty sure that the code would *fail* in this case, rather than returning incorrect output. So I think your workaround is safe to use for your example.

**Comment by nmutto** [comment]
@spxiwh Thank you for your reply. Given the structure of my code I think I cannot put the creation of the `FDomainDetFrameGenerator` inside the parallel loop. Luckily enough, I am not working with time-domain waveforms and I don't think I'll need them for the code I am developing. However, this is good to know for future projects. Thank you again for you support.
