### ISSUE TITLE
banksim error v2.0.4

### ISSUE THREAD

**Issue by MariaAssiduo** [gwastro/pycbc#4067]
Hi, I'm trying to use banksim using the latest version of pycbc, running the source:

`source /cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_8/virtualenv/pycbc-v2.0.4/bin/activate`

But I still encounter the same error I tried to overcome in the past [link](https://github.com/gwastro/pycbc/issues/3814)

```
(igwn-py39-20220317) (pycbc-v2.0.4) [maria.assiduo@ldas-pcdev6 test_newVers_pycbc]$ pycbc_make_banksim --config banksim.ini 
2022-06-23 02:28:30,641 Making workspace directories
2022-06-23 02:28:30,696 Copying scripts
2022-06-23 02:28:30,788 Creating injection file
2022-06-23 02:28:33,950 Splitting template bank
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20220317/bin/pycbc_splitbank", line 127, in <module>
    tt = sorted(template_bank_table, cmp=mchirp_sort)
TypeError: 'cmp' is an invalid keyword argument for sort()
2022-06-23 02:30:32,071 Splitting injection file
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20220317/bin/pycbc_splitbank", line 127, in <module>
    tt = sorted(template_bank_table, cmp=mchirp_sort)
TypeError: 'cmp' is an invalid keyword argument for sort()
```
If I try to git clone the new version to make changes by myself, I get the following error message:  (using virtualenv -p /cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20220317/bin/python pycbc_Python3)

AssertionError: Filename /home/maria.assiduo/.local/lib/python3.9/site-packages/setuptools/_distutils does not start with any of these prefixes: ['/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20220317', '/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20220317']

If I try without conda env at the end I get the error:
Requirement already satisfied: lscsoft-glue>=1.59.3 in /home/maria.assiduo/gwastro3_pycbc/pycbc_Python3/lib/python3.6/site-packages (from PyCBC==2.0.4) (3.0.1)
ERROR: Package 'pycbc' requires a different Python: 3.6.8 not in '>=3.7'

Any help? Thanks in advance.

**Comment by titodalcanton** [comment]
Hi @MariaAssiduo, I see a couple separate issues in what you posted.

You first tried to source `pycbc-v2.0.4`. However, the error you reported implies that you are still calling `/cvmfs/oasis.opensciencegrid.org/ligo/sw/conda/envs/igwn-py39-20220317/bin/pycbc_splitbank` (i.e. the PyCBC version that is in the `igwn-py39-20220317` env), which is clearly older than the fix for #3814. You are mixing a Conda env and a virtualenv. Source *either* igwn-py39 *or* pycbc-v2.0.4, but not one after the other.

You then tried to create your own virtualenv starting from the igwn-py39 Python (this is the solution I would personally choose). However, you apparently have a (possibly broken) Python environment in `~/.local`, which appears to interfere with your new virtualenv. My advice here is to just remove anything related to Python from your `~/.local` directory (in particular `~/.local/lib/python*`, but also the corresponding stuff in `~/.local/bin`). I also had many problems with stuff in `~/.local/lib/python*` in the past. Needless to say, make sure that you are not removing anything important. Then log out and back in, make sure no Python env is sourced, and source your virtualenv.
