### ISSUE TITLE
pycbc/banksim

### ISSUE THREAD

**Issue by MariaAssiduo** [gwastro/pycbc#4155]
Hi. banksim jobs continue to fail with the following kind of error:

```
(pycbc_Python3) [maria.assiduo@ldas-osg banksim_xphm_100-200]$ grep -1  4e41ca33898caf184fa504c337aafd0d *sh
banksim.sh-
banksim.sh:# Job 4e41ca33898caf184fa504c337aafd0d
banksim.sh-scripts/pycbc_banksim_match_combine --inj-num 3 --output-file match/match3.dat
```

Having a look in the directory match, the file match3.dat is not missing. It is repeated for others inj num. There are no other info about the error message, what exactly does it means?

PATH DIR -> /home/maria.assiduo/test_gwastro6/banksim_xphm_100-200/

Thank you in advance.

**Comment by spxiwh** [comment]
Hi @MariaAssiduo I'm not really sure what's going on here. Something weird is happening with condor (maybe some configuration change?), and I think this is making things not work. If I look at a failing log file:

`vi log/pycbc_banksim_match_combine`

after a lot of warnings that I wouldn't expect to see, because we're not using Singularity/Apptainer, I see the error:

```
Traceback (most recent call last):
  File "/srv//condor_exec.exe", line 21, in <module>
    indices = array(matches, dtype=dtypef)['match'].argmax(0)
ValueError: attempt to get argmax of an empty sequence
```

This would suggest that the code hasn't found any matches, but the location of the executable is strange, suggesting condor has moved everything to an execute directory, where it then cannot find the input files. In the past the job runs in the same directory as it is submitted.

If I run the command from the command line:

```
./scripts/pycbc_banksim_match_combine --inj-num 147 --output-file ~/TMPDELETE.dat
```

it runs fine.

.... I'm then not really sure what to suggest. If this is due to condor updates/changes on CIT, then we will need to update the banksim code (but updating this code, and/or merging it with the newer `bank_verificator` and ensuring adequate documentation, has been on the PyCBC to-do list for some time, and no-one has found the time to do it yet).

**Comment by titodalcanton** [comment]
I have been running a few banksims in the last days, and noted down a few bugs/things that I would like to improve, but I do not seem to see a problem like this. So I am closing, but feel free to reopen if this keeps happening.
