### ISSUE TITLE
Importing PyCBC modules sets Numpy random state for all child processes when multi-processing.

### ISSUE THREAD

**Issue by xli2522** [gwastro/pycbc#4217]
[Not urgent]
### Issue:
Running `pycbc.noise.noise_from_psd(tsamples, delta_t, psd)` without specifying the random seed results in identical waveforms across all child processes when multi-processing using the `multiprocessing` package for Python.

### Environment:
MacOS BigSur version 11.2.3
Python 3.10
PyCBC Version: 0.0a8419

### Issue Reproduction:
```Python
import pycbc
import numpy as np
import random
import matplotlib.pyplot as plt
from multiprocessing import Pool

def seed_gen_random(seed=None):
    if seed is None:
        seed = random.random()
    print(seed)
    return
def seed_gen_numpy(seed=None):
    if seed is None:
        seed = np.random.randint(2**32)
    print(seed)
    return


if __name__ == '__main__':

    pool = Pool(processes=5)
    pool.map(seed_gen_numpy, [None]*5)
    pool.map(seed_gen_random, [None] * 5)
    pool.terminate()
```
Outputs:
```
12671606818
12671606818
12671606818
12671606818
12671606818
0.1825130165926685
0.2750317271131507
0.3515885086694659
0.20769229958012225
0.3525480636829891
```

### Details:
1. This issue only happens when PyCBC is imported. The same thing also happens if a portion of the PyCBC module is imported ie: ```import pycbc.noise``` or ```import pycbc.psd``` 
2. This issue only happens to Numpy.random, it does not affect Python's built-in random module (see ```seed_gen_random```).
3. It seems like the direct cause of identical noise waveforms across all child processes is the random seed generated in ```pycbc.noise.gaussian``` suffering from the above issue:
```Python
if seed is None:
        seed = numpy.random.randint(2**32)
``` 
4. Based on my understanding, Numpy.random.randint used to have this behaviour by itself (not sure if it was intentional or not) but it was changed in a later update. 

I am unsure if this is a behaviour expected by PyCBC developers but I find it worth pointing out.

Best.

**Comment by spxiwh** [comment]
@xli2522 Thanks for the notification about this. Indeed, I think we would expect something like this to generate different random numbers.

I don't think this is a PyCBC specific problem. If I take your example code and remove the `import pycbc` I still see the same random numbers generated by numpy (using numpy version 1.23.5).

We do use code like 

```
if seed is None:
        seed = numpy.random.randint(2**32)
```

in a few places. I think that including the `os.getpid()` as suggested here https://stackoverflow.com/questions/9209078/using-python-multiprocessing-with-different-random-seed-for-each-process would solve this, but I'm not sure what you mean by "Based on my understanding, Numpy.random.randint used to have this behaviour by itself (not sure if it was intentional or not) but it was changed in a later update.". I am *not* seeing this, unless it's been changed in a very recent numpy (which currently causes issues with one of PyCBC's dependencies).

**Comment by xli2522** [comment]
Thanks for the reply. This is interesting, because I get different values when PyCBC is not imported, commenting out ```import pycbc``` gives me
```
8886778570
13742966958
13508552515
286204216
1856127668
0.47383143823858487
0.7697099175554277
0.3605470179334006
0.5023635585780554
0.4646016008958074
```
I get similar results with both Numpy 1.23.1 and 1.24.1. The reason I said Numpy used to have this behaviour is because of [https://github.com/numpy/numpy/issues/9248](https://github.com/numpy/numpy/issues/9248) and [https://github.com/numpy/numpy/issues/9650](https://github.com/numpy/numpy/issues/9650). But you are right it is easily fixable on my end with `getpid()`. 

Best.

**Comment by xli2522** [comment]
I tested Numpy random again on Google Colab server (Python 3.8.16; Numpy 1.23.1), Windows 11 (Python 3.6; 3.9; 3.10; Numpy 1.19; 1.23; 1.24), and MacOS BigSur (AMD CPU) (Python 3.10; Numpy 1.23). Google Colab gave the same random values (as you described) but all others gave different values. I think this is a problem deep in Python and Numpy and how they interact with the system. Thank you again for the info!

Best.
