### ISSUE TITLE
Some visible loud missed injections are not in injection minifollowups

### ISSUE THREAD

**Issue by tdent** [gwastro/pycbc#4601]
In the new search pipeline including single-ifo candidates and with gating veto windows, quite often we see loud (SNR>100) missed injections in the f/m plots that are not in the inj minifollowups. 

Possible explanations for this: 
 - These may be single-ifo-time injections that are missed and plotted but are not included in minifollowups
 - These may be injections inside gating veto windows that are missed and plotted but are not included in minifollowups 

In either case we would like to get the f/m plots and minifollowups consistent ; probably we do want to include gating-vetoed missed inj in any case.

**Comment by titodalcanton** [comment]
This appears to be due to the minifollowup sorting the missed injections in order of decreasing *second-highest* optimal SNR. Given that many injections fall in single-detector time, the second-highest SNR is zero, and those injections drop to the bottom of the list.

However, we now do have the ability to detect signals that are loud in one detector only. So it would probably be better for the minifollowup to sort missed injections by *network* optimal SNR instead.

As I type this, I seem to recall that this was indeed discussed a while ago in another issue or pull request…

**Comment by titodalcanton** [comment]
Possibly related to this: #4498

**Comment by tdent** [comment]
Addressed by #4602
