### ISSUE TITLE
On source/off source implementation

### ISSUE THREAD

**Issue by sebastiangomezlopez** [gwastro/pycbc#4659]
I'm creating this issue since I've been discussing with @pannarale  the fact that the new PyGRB workflow generator, i.e. pycbc_make_offline_grb_workflow [code](https://github.com/sebastiangomezlopez/pycbc/blob/master/bin/pygrb/pycbc_make_offline_grb_workflow) has no on-source/off-source separation when it comes to doing/presenting the typical closed box and open box analysis.

Currently, I'm working on a local installation on CIT, but once I'm done, I'll post the code on [my fork](https://github.com/sebastiangomezlopez/pycbc/tree/on-off-pygrb).

I'm specifically looking at functions like `get_triggered_coherent_segment` and `generate_triggered_segment` living in `pycbc.workflow.segment` and seeing how to integrate them with the `pycbc_make_offline_grb_workflow` code.

As of my understanding, following the old workflow design would mean letting the matched filtering engine compute the results for all segments, and use functions like `get_triggered_coherent_segment` to separate the segments containing the on-source and off-source windows at the workflow level. Later make the postprocessing code present both separately as closed and open box pages.

@spxiwh , @titodalcanton  I'm keeping both of you on this thread and would like to know if you have any thoughts or opinions on this. Let us know

**Comment by spxiwh** [comment]
My suggestion would be to not worry about this at the workflow level and instead deal with it in various plotting codes.

So instead of having a result file for "ONSOURCE" and "OFFSOURCE", just have one result file containing all triggers (including time slides), and just plot whatever subset of this is needed.

I think that some version of `generate_triggered_segment` is still required as you would need to identify the on/offsource and buffer segment. `segmentsUtils.tosegwizard` should definitely be removed, you could just store all the information in a single file (e.g. an XML segment file / HDF file). That file could then be passed directly to any plotting/post-processing code so it can figure out what segments it might need for whatever it is doing.
